# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('graph', ['core'])
    module.source = [
        'model/graph.cc',
        'model/vertex.cc',
        'helper/graph-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('graph')
    module_test.source = [
        'test/graph-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'graph'
    headers.source = [
        'model/graph.h',
        'model/vertex.h',
        'helper/graph-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

